"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/layouts/Navbar";
import { ThemeProvider } from "@/context/theme-context";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Le Thanh Dat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/x-icon" />
      </head>
      <body
        suppressHydrationWarning={true}
        className={`${inter.className} transition-colors duration-1000`}
        style={{ backgroundColor: "var(--color-primary-bg)" }}
      >
        <ThemeProvider>
          <NextTopLoader
            color="var(--color-primary-text)"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            showSpinner={false}
          />
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
